// <auto-generated />
using System;
using ForumApp.Web;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumApp.Web.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    [Migration("20230604152942_PostSeeding")]
    partial class PostSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForumApp.Web.Model.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("23ff44a7-3f9f-4a87-b327-6c85d17b1f0b"),
                            Content = "Let me put some extra content so the validation would be okay.",
                            Title = "This is the first Post"
                        },
                        new
                        {
                            Id = new Guid("6b219522-f4d5-415f-b972-fe8022565b04"),
                            Content = "Let me put some extra content so the validation would be okay.",
                            Title = "This is the second Post"
                        },
                        new
                        {
                            Id = new Guid("fd976b26-47e9-4f19-9e0b-cb558810daa4"),
                            Content = "Let me put some extra content so the validation would be okay.",
                            Title = "This is the third and last Post"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
